name: news-signal-pipeline
networks:
  redpanda_network:
    external: true
    name: redpanda_network
services:
  news:
    build:
      context: ../services/news
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/news/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    volumes:
      - news_named_volume:/app/state
    # restart: always

  news-signal:
    build:
      context: ../services/news-signal
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/news-signal/settings.env
      # - ../services/news-signal/anthropic_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - MODEL=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - news_signal_named_volume:/app/state
    # restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/live.settings.news-signal.env
      - ../services/to-feature-store/hops_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    volumes:
      - fs_named_volume:/app/state     # State for fs service
    # restart: always

volumes:
  news_named_volume:
    # external: true
  news_signal_named_volume:
    # external: true
  fs_named_volume:
    # external: true
