name: news-signal-pipeline-historical
networks:
  redpanda_network:
    external: true
    name: redpanda_network
services:
  news:
    build:
      context: ../services/news
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    # env_file:
    #   - ../services/news/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_TOPIC=news_historical_${RUN_ID}
      - DATA_SOURCE=historical
      - HISTORICAL_DATA_SOURCE_CSV_FILE=/app/data/cryptopanic_news.csv
    volumes:
      - ../services/news/data:/app/data  # Historical data from CSV
      - news_named_volume:/app/state     # State for news service
    restart: always

  news-signal:
    build:
      context: ../services/news-signal
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    # env_file:
    #   - ../services/news-signal/settings.env
    #   # - ../services/news-signal/anthropic_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=news_historical_${RUN_ID}
      - KAFKA_OUTPUT_TOPIC=news_signal_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=news_signal_historical_${RUN_ID}
      - MODEL=ollama # [ollama, anthropic, dummy]TODO: change to our fine tuned model (once we manage to export it!)
      - DATA_SOURCE=historical
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - news_signal_named_volume:/app/state
    restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      # - ../services/to-feature-store/live.settings.news-signal.env
      - ../services/to-feature-store/hops_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=news_signal_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=to_feature_store_news_signal_historical_${RUN_ID}
      - FEATURE_GROUP_NAME=news_signals
      - FEATURE_GROUP_VERSION=1
      - FEATURE_GROUP_PRIMARY_KEYS=["coin"]
      - FEATURE_GROUP_EVENT_TIME=timestamp_ms
      - DATA_SOURCE=historical
    volumes:
      - fs_named_volume:/app/state     # State for fs service
    restart: always

volumes:
  news_named_volume:
    # external: true
  news_signal_named_volume:
    # external: true
  fs_named_volume:
    # external: true
