name: technical-indicators-pipeline
networks:
  redpanda_network:
    external: true # This network is created in the redpanda.yml file.
    name: redpanda_network

services:
  trades:
    build:
      context: ../services/trades
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/trades/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always # This will restart the container if it crashes. Similar to a Kubernetes pod.

  candles:
    build:
      context: ../services/candles
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/candles/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always

  technical-indicators:
    build:
      context: ../services/technical-indicators
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/technical-indicators/settings.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/settings.env
      - ../services/to-feature-store/hops_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
    restart: always